Site Vendinha InterFocus/Models/Cliente.cs
using Newtonsoft.Json;

namespace Site_Vendinha_InterFocus.Models
{
    public class Cliente
    {
        public Guid ClienteId { get; set; }
        public string ClienteName { get; set; }
        public DateTime DataNascimento { get; set; }
        public string Email { get; set; }

        [JsonIgnore]
        public decimal ValorTotalDividas { get; set; }
    }
}

Site Vendinha InterFocus/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Site_Vendinha_InterFocus.Models;
using System.Security.Policy;
using System.Text;

namespace Site_Vendinha_InterFocus.Controllers
{
    public class ClienteController : Controller
    {
        private readonly HttpClient Request;
        // GET: ClienteController

        public ClienteController()
        {
            Request = new HttpClient();
            Request.BaseAddress = new Uri("https://localhost:7200/");
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: ClienteController/Details/5
        public async Task<ActionResult> DetailsAsync(Guid id)
        {
            var clienteJson = await Request.GetStringAsync($"api/Clientes/{id.ToString()}");
            var cliente = JsonConvert.DeserializeObject<Cliente>(clienteJson);
            return View(cliente);
        }

        // GET: ClienteController/Create
        public ActionResult Create()
        {
            var cliente = new Cliente() {ClienteId = Guid.NewGuid() };
            return View(cliente);
        }

        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateClienteAsync(Cliente cliente)
        {
            try
            {
                var ClienteJson = JsonConvert.SerializeObject(cliente);
                var requestContent = new StringContent(ClienteJson ,Encoding.UTF8, "application/json");
                await Request.PostAsync("api/Clientes/", requestContent);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<ActionResult> EditAsync(Guid id)
        {
            var clienteJson = await Request.GetStringAsync($"api/Clientes/{id.ToString()}");
            var cliente = JsonConvert.DeserializeObject<Cliente>(clienteJson);
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(Guid id, Cliente cliente)
        {
            try
            {
                var ClienteJson = JsonConvert.SerializeObject(cliente);
                var requestContent = new StringContent(ClienteJson, Encoding.UTF8, "application/json");
                await Request.PutAsync($"api/Clientes/{cliente.ClienteId}", requestContent);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<ActionResult> DeleteAsync(Guid id)
        {
            var clienteJson = await Request.GetStringAsync($"api/Clientes/{id.ToString()}");
            var cliente = JsonConvert.DeserializeObject<Cliente>(clienteJson);
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(Guid id, Cliente cliente)
        {
            try
            {
                await Request.DeleteAsync($"api/Clientes/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> ListAsync()
        {
            var clienteJson = await Request.GetStringAsync("api/Clientes");
            var clientes = JsonConvert.DeserializeObject<List<Cliente>>(clienteJson);

            var DividasJson = await Request.GetStringAsync("api/Dividas");
            var Dividas = JsonConvert.DeserializeObject<List<Divida>>(DividasJson);

            clientes.ForEach(c => c.ValorTotalDividas = Dividas.Where(d => d.ClienteId == c.ClienteId)
                                                               .Select(d => d.ValorDivida)
                                                               .Sum());

            return View(clientes);
        }
    }
}

Site Vendinha InterFocus/Controllers/DividaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Site_Vendinha_InterFocus.Models;
using System.Globalization;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

namespace Site_Vendinha_InterFocus.Controllers
{
    public class DividaController : Controller
    {
        private readonly HttpClient Request;

        public DividaController()
        {
            Request = new HttpClient();
            Request.BaseAddress = new Uri("https://localhost:7200/");
        }
        // GET: DividaController
        public ActionResult Index()
        {
            return View();
        }
        private float ConvertValorToFloat(string valor)
        {

            CultureInfo formato = null;
            formato = (CultureInfo)CultureInfo.InvariantCulture.Clone();
            formato.NumberFormat.NumberDecimalSeparator = ",";
            formato.NumberFormat.NumberGroupSeparator = ".";
            return float.Parse(valor.Replace("R$", ""), formato);

        }
        // GET: DividaController/Details/5
        public async Task<ActionResult> DetailsAsync(Guid id)
        {
            var dividaJson = await Request.GetStringAsync($"api/Dividas/{id.ToString()}");
            var divida = JsonConvert.DeserializeObject<Divida>(dividaJson);
            return View(divida);
        }

        // GET: DividaController/Create
        public async Task<ActionResult> CreateAsync(Guid? clienteId)
        {
            var clienteJson = await Request.GetStringAsync("api/Clientes");
            var clientes = JsonConvert.DeserializeObject<List<Cliente>>(clienteJson);


            if (clienteId == null)
                ViewBag.Clientes = clientes.Select(c => new SelectListItem { Text = c.ClienteName, Value = c.ClienteId.ToString()});
            else
                ViewBag.Clientes = clientes.Where(cl => cl.ClienteId == clienteId).Select(c => new SelectListItem { Text = c.ClienteName, Value = c.ClienteId.ToString() });

            var divida = new Divida() { 
                DividaId = Guid.NewGuid(),
                DataDeCriacao = DateTime.Now,
                DataDePagamento = DateTime.Now.AddDays(30)
            };
            return View(divida);
        }

        // POST: DividaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(Divida divida)
        {
            try
            {
                divida.ValorDivida = (decimal)ConvertValorToFloat(divida.Valor);
                var DividaJson = JsonConvert.SerializeObject(divida);
                var requestContent = new StringContent(DividaJson, Encoding.UTF8, "application/json");
                var DividasJson = await Request.GetStringAsync("api/Dividas");
                var Dividas = JsonConvert.DeserializeObject<List<Divida>>(DividasJson);              
                var TemDividasEmAberto = Dividas.Where(d => d.ClienteId == divida.ClienteId && d.EstaPaga == false).ToList();
                if (TemDividasEmAberto.Count > 0)
                    return RedirectToAction(nameof(NaoFoiPossivelCadastrar));

                await Request.PostAsync("api/Dividas/", requestContent);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DividaController/Edit/5
        public async Task<ActionResult> EditAsync(Guid id)
        {
            var dividaJson = await Request.GetStringAsync($"api/Dividas/{id.ToString()}");
            var divida = JsonConvert.DeserializeObject<Divida>(dividaJson);
            divida.Valor = divida.ValorDivida == 0 ? "" : divida.ValorDivida.ToString();
            return View(divida);
        }

        // POST: DividaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(Guid id, Divida divida)
        {
            try
            {
                if (divida.Valor.Contains(","))
                {
                    divida.Valor.Remove(divida.Valor.Length - 1);
                    divida.Valor = $"R$ {divida.Valor}";
                }
                divida.ValorDivida = (decimal)ConvertValorToFloat(divida.Valor);
                var DividaJson = JsonConvert.SerializeObject(divida);
                var requestContent = new StringContent(DividaJson, Encoding.UTF8, "application/json");
                await Request.PutAsync($"api/Dividas/{divida.DividaId}", requestContent);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DividaController/Delete/5
        public async Task<ActionResult> DeleteAsync(Guid id)
        {
            var dividaJson = await Request.GetStringAsync($"api/Dividas/{id.ToString()}");
            var divida = JsonConvert.DeserializeObject<Divida>(dividaJson);
            return View(divida);
        }

        // POST: DividaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(Guid id, Divida divida)
        {
            try
            {
                await Request.DeleteAsync($"api/Dividas/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> ListAsync(Guid? clienteId )
        {
            var clienteJson = await Request.GetStringAsync("api/Clientes");
            var clientes = JsonConvert.DeserializeObject<List<Cliente>>(clienteJson);

            var DividasJson = await Request.GetStringAsync("api/Dividas");
            var Dividas = JsonConvert.DeserializeObject<List<Divida>>(DividasJson);

            Dividas.ForEach(d => d.nomeCliente = clientes.FirstOrDefault(c => c.ClienteId == d.ClienteId).ClienteName);

            if(clienteId != null)
                return View(Dividas.Where(d => d.ClienteId == clienteId));

            return View(Dividas);
        }

        public ActionResult NaoFoiPossivelCadastrar()
        {
            return View();
        }
    }
}

Site Vendinha InterFocus/Views/Cliente/Create.cshtml
@model Site_Vendinha_InterFocus.Models.Cliente

@{
    ViewData["Title"] = "CreateCliente";
}

<h1>Cadastrar novo Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClienteName" class="control-label"></label>
                <input asp-for="ClienteName" class="form-control" />
                <span asp-validation-for="ClienteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Site Vendinha InterFocus/Views/Cliente/Delete.cshtml
@model Site_Vendinha_InterFocus.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Deletar</h1>

<h3>Deletar cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClienteName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClienteName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para clientes cadastrados</a>
    </form>
</div>

Site Vendinha InterFocus/Views/Cliente/Details.cshtml
@model Site_Vendinha_InterFocus.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClienteName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClienteName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.ClienteId  }) |
    <a asp-action="List">Voltar para clientes cadastrados</a>
</div>

Site Vendinha InterFocus/Views/Cliente/Edit.cshtml
@model Site_Vendinha_InterFocus.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>View</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.ClienteId)
            <div class="form-group">
                <label asp-for="ClienteName" class="control-label"></label>
                <input asp-for="ClienteName" class="form-control" />
                <span asp-validation-for="ClienteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Site Vendinha InterFocus/Views/Cliente/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Operação realizada com sucesso</h1>

@Html.ActionLink("Voltar para lista de clientes", "List","Cliente")

Site Vendinha InterFocus/Views/Cliente/List.cshtml
@model IEnumerable<Site_Vendinha_InterFocus.Models.Cliente>

@{
    ViewData["Title"] = "List";
}

<h1>Clientes Cadastrados</h1>

<p>
    <a class="btn btn-success" asp-action="Create">Cadastrar novo cliente</a>
</p>
<table class="table" id="tableVenda">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClienteName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorTotalDividas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClienteName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorTotalDividas)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ClienteId}) |
                @Html.ActionLink("Details", "Details", new {id = item.ClienteId }) |
                @Html.ActionLink("Delete", "Delete", new {id = item.ClienteId })|
                @Html.ActionLink("Lista de dívidas","List", "Divida", new {clienteId = item.ClienteId }, new {@class="btn btn-primary"}) |
                @Html.ActionLink("Criar nova divida","Create", "Divida", new {clienteId = item.ClienteId }, new {@class="btn btn-secondary"})
            </td>
        </tr>
}
    </tbody>
</table>